language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly
install:
  - composer -q install --prefer-dist
  - touch .env
  - php artisan key:generate
  - ./vendor/bin/phpunit --coverage-text
